# Generated by Django 4.2.5 on 2023-09-17 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_table_articletag'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ArticleTag',
            new_name='Scope',
        ),
    ]
