# Generated by Django 4.2.5 on 2023-09-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_articletag_scope'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag_table',
            new_name='TagTable',
        ),
        migrations.AlterModelOptions(
            name='tagtable',
            options={'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
    ]
